### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by axelboc** [numtide/clean-git-action#2]
Thanks for making this very convenient action. 😊 

I'm getting a node-12 deprecation warning in GitHub when using `numtide/clean-git-action@v1`, as documented in the README:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: numtide/clean-git-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

I see the [latest commit](https://github.com/numtide/clean-git-action/commit/3d1ca34ae188e807ec16c778588acfe619074053) bumped Node to v16, so I guess it's just a matter of updating the README and creating a `v2` tag?

**Comment by zimbatm** [comment]
fixed!
